### ISSUE TITLE
"AttributeError: cython_sources" when building the Docker image

### ISSUE THREAD

**Issue by bathienle** [cytomine/Cytomine-installer#2]
Hello,
When building the Docker image, I have the following issue with the installation of PyYAML.

```
#0 1.105 Collecting PyYAML==6.0 (from cytomine-installer==0.0.0)                                                                                                                                                   
#0 1.174   Downloading PyYAML-6.0.tar.gz (124 kB)
#0 1.222      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 2.9 MB/s eta 0:00:00
#0 1.346   Installing build dependencies: started
#0 4.779   Installing build dependencies: finished with status 'done'
#0 4.780   Getting requirements to build wheel: started
#0 4.984   Getting requirements to build wheel: finished with status 'error'
#0 5.005   error: subprocess-exited-with-error
#0 5.005   
#0 5.005   × Getting requirements to build wheel did not run successfully.
#0 5.005   │ exit code: 1
#0 5.005   ╰─> [54 lines of output]
#0 5.005       running egg_info
#0 5.005       writing lib/PyYAML.egg-info/PKG-INFO
#0 5.005       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#0 5.005       writing top-level names to lib/PyYAML.egg-info/top_level.txt
#0 5.005       Traceback (most recent call last):
#0 5.005         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 5.005           main()
#0 5.005         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 5.005           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 5.005                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 5.005         File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#0 5.005           return hook(config_settings)
#0 5.005                  ^^^^^^^^^^^^^^^^^^^^^
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
#0 5.005           return self._get_build_requires(config_settings, requirements=['wheel'])
#0 5.005                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
#0 5.005           self.run_setup()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
#0 5.005           exec(code, locals())
#0 5.005         File "<string>", line 288, in <module>
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 107, in setup
#0 5.005           return distutils.core.setup(**attrs)
#0 5.005                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 5.005           return run_commands(dist)
#0 5.005                  ^^^^^^^^^^^^^^^^^^
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 5.005           dist.run_commands()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#0 5.005           self.run_command(cmd)
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 1233, in run_command
#0 5.005           super().run_command(command)
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#0 5.005           cmd_obj.run()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 319, in run
#0 5.005           self.find_sources()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
#0 5.005           mm.run()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 549, in run
#0 5.005           self.add_defaults()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
#0 5.005           sdist.add_defaults(self)
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
#0 5.005           super().add_defaults()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
#0 5.005           self._add_defaults_ext()
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
#0 5.005           self.filelist.extend(build_ext.get_source_files())
#0 5.005                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 5.005         File "<string>", line 204, in get_source_files
#0 5.005         File "/tmp/pip-build-env-gouyrkpv/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#0 5.005           raise AttributeError(attr)
#0 5.005       AttributeError: cython_sources
#0 5.005       [end of output]
#0 5.005   
#0 5.005   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 5.007 error: subprocess-exited-with-error
#0 5.007 
#0 5.007 × Getting requirements to build wheel did not run successfully.
#0 5.007 │ exit code: 1
#0 5.007 ╰─> See above for output.
#0 5.007 
#0 5.007 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:19
--------------------
  17 |     COPY requirements.txt /app/requirements.txt
  18 |     COPY cytomine_installer /app/cytomine_installer
  19 | >>> RUN pip install -e .
  20 |     
  21 |     ARG IMAGE_VERSION
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -e ." did not complete successfully: exit code: 1
``` 

Someone has had the same issue with PyYAML==6.0.0 https://github.com/yaml/pyyaml/issues/724#issuecomment-1638547611

**Comment by waliens** [comment]
Hi  @bathienle 

Latest build was successful on our side 2 months ago (with PyYAML 6.0.0).  Maybe something has changed since then in their lib ? We will look into this issue when we build the next version (not planned as of now).
  
Could you share your use case why you need to rebuild the image ? If you are not adding features to the installer, I suggest that you use the pre-built image from Dockerhub: [cytomine/installer:latest](https://hub.docker.com/r/cytomine/installer).

**Comment by bathienle** [comment]
Hello @waliens,

For the use case, I was just setting up a github action that build and push the docker image.
But yes, I will use your image from Dockerhub.

**Comment by waliens** [comment]
Fixed in https://github.com/cytomine/Cytomine-installer/releases/tag/5.0.0
